### PR TITLE
Handle process.env

### PR DESCRIPTION
**Pull request by firatoezcan-2**
Something I just had to patch right now for my project. Sorry for no tests

### CODE REVIEW

**Comment by garronej** [comment]
Hey man thanks for the pr!

**Comment by garronej** [comment]
And sorry for the delay

**Comment by garronej** [comment]
Oops I guess I already had a case for this:  

image

**Comment by firatoezcan-2** [comment]
Was there a reason to do it that way? I figured this was maybe a regression because using `node:process` was not working for me with Supabase functions. 

We did switch over to something else however and I'm not sure how Deno 2.0 is going to handle stuff like this, but maybe having this be configurable would be great.

Then again, if no one ever raised this as an issue, then it may just be a special setup I was implementing (and it definitely felt "off-the-mark").

Btw, great project! It did exactly what it said it'd do :+1:

**Comment by garronej** [comment]
Hello @firatoezcan-2,  

> Was there a reason to do it that way? I figured this was maybe a regression because using node:process was not working for me with Supabase functions.

Well the reason was that there is an official polyfill for node's process. I wasn't aware that it would cause issue on some serverless engine.  

> We did switch over to something else however and I'm not sure how Deno 2.0 is going to handle stuff like this, but maybe having this be configurable would be great.  

Regarding  this specific thing, deno 2 adds `process` to the global so there's no need to implicitely `import process from 'node:process'` anymore. However it's still recomended.  
https://youtu.be/DoU5DLl2Aq4?si=5wuNFFNFYgzCd2nd&t=265  

> Then again, if no one ever raised this as an issue, then it may just be a special setup I was implementing (and it definitely felt "off-the-mark").  

Yeah, that's why I rolled back the change. It's ok to add support for something that wasn't previously supported by Denoify and yo change how things currently works.  
While your proposed change might be better I'm too afraid it will break things for pepole if introduced, I can't confidently gauge the impact that it would have.  

I can sugest to options for your issue:  
1) [Use a `.deno.ts` file](https://docs.denoify.land/.deno.ts-files). Create a small file from where you export your envs like:  
`env.ts`
```ts
export const env = process.env;
```
And manually create a specific implementation for deno:  
`env.deno.ts`
```ts
export const env = Deno.env.toObject();
```
And then through out your codebase you can import this file instead of using `process.env` directly.  

2) If refactorying your codebase in this way isn't an option you can levrage [patch-package](https://www.npmjs.com/package/patch-package) to apply the change that you made in this PR to your local Denoify install.  

> Btw, great project! It did exactly what it said it'd do 👍  

Thank you, that's very kind of you to say. IMO the project is a bit overpromising but I'm glad it (mostly) did the trick for you.

**Pull request merged**
