### PR TITLE
add support for rxjs/webSocket in replacer

### PR DESCRIPTION
**Pull request by marcushultman**
use skypack CDN with `X-TypeScript-Types` header support

### CODE REVIEW

**Comment by marcushultman** [comment]
@garronej I didn't see any guidelines in regards to which esm module cdn to use. So I just now discovered that pika switched name and had updated documentation for Deno.

**Comment by marcushultman** [comment]
@garronej I added your semicolon. I suggest you configure a linter for this project. Also the Codacy feedback said: "Not up to standards. This pull request quality could be better.". This feedback is **not** nicely worded nor constructive, an frankly a subpar developer experience. I suggest you adress that too.

**Comment by garronej** [comment]
> use skypack CDN with `X-TypeScript-Types` header support

Good job! Thank you

> @garronej I didn't see any guidelines in regards to which esm module cdn to use. So I just now discovered that pika switched name and had updated documentation for Deno.

There are no guidelines, whatever works. 

> @garronej I added your semicolon. I suggest you configure a linter for this project. Also the Codacy feedback said: "Not up to standards. This pull request quality could be better.". This feedback is **not** nicely worded nor constructive, an frankly a subpar developer experience. I suggest you adress that too.

Ok I will setup a linter 👍  and OMG fuck Codacy, I just tried it out one day to see what it was saying about my code. I thought the suggestion where mostly garbage so I forgot about it and now it is insulting contributors. I removed it.

**Comment by marcushultman** [comment]
@garronej thank you! Happy to help :)

**Pull request merged**
